app:
  name: blog-service
  env: dev
  addr: ":8080"

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: Ab123456
  dbname: blog
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_lifetime: 30


jwt:
  secret: blog-secret
  expire_days: 1

log:
  level: debug        # debug | info | warn | error
  format: console       # json | console
  filename: logs/app.log
  max_size: 10      # MB
  max_backups: 3
  max_age: 10        # days

timeout:
  default: 2s
  routes:
    /api/posts/hot: 500ms
    /api/posts: 3s